-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Profiles (Goalies & Parents linked)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text, -- This matches the 'Guardian Email'
  role text default 'parent', -- 'parent', 'coach', 'admin'
  
  -- Goalie Specific
  goalie_name text, -- Combined 'Player First Name' + 'Player Last Name'
  parent_name text, -- 'Guardian First & Last Name'
  parent_phone text, -- 'Guardian Phone Number'
  
  dob date,
  grad_year int, -- 'Player Graduation Year'
  team text, -- 'Club Team Name'
  
  -- Lacrosse Specific
  us_lacrosse_id text, -- 'US Lacrosse Membership Number'
  waiver_signed boolean default false, -- 'ENTER NAME AND DATE...'
  
  -- System Status
  status text default 'pending', -- 'active', 'pending', 'renew_needed'
  unique_id text, -- The GC-XXXX ID generated by system
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Sessions (Tracking Progress)
create table public.sessions (
  id uuid default uuid_generate_v4() primary key,
  goalie_id uuid references public.profiles(id),
  
  session_number int default 1,
  lesson_number int default 0, -- 0 to 4
  
  is_active boolean default true,
  last_lesson_date timestamp with time zone,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Schedule Requests (Coach Inbox)
create table public.schedule_requests (
  id uuid default uuid_generate_v4() primary key,
  goalie_id uuid references public.profiles(id),
  parent_id uuid references public.profiles(id), -- optional linkage
  
  requested_date timestamp with time zone,
  note text,
  status text default 'pending', -- 'pending', 'accepted', 'declined'
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Session Logs (Reviews)
create table public.reviews (
  id uuid default uuid_generate_v4() primary key,
  session_id uuid references public.sessions(id),
  goalie_id uuid references public.profiles(id),
  
  rating_glove int,
  rating_blocker int,
  rating_pads int,
  rating_iq int,
  
  notes text,
  coach_id uuid references public.profiles(id),
  
  marketable_stat text, -- e.g. "Glove Hand Precision"
  marketable_quote text,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.sessions enable row level security;
alter table public.schedule_requests enable row level security;
alter table public.reviews enable row level security;

-- Policies (Simple Start)
create policy "Public Content" on public.profiles for select using (true);
create policy "Coaches can view all" on public.profiles for select using (auth.uid() in (select id from profiles where role = 'coach' or role = 'admin'));
